[network]
nodes = 8
space_min = 0.0
space_max = 200.0
gps_err = 45.0    # Огромная ошибка старта
dist_err = 0.1    # Точные расстояния

[hyperparams]
alpha = 0.02
lambda = 0.01   # Почти не доверяем мнимым координатам
eps = 0.0001
max_iter = 5000 # Потребуется больше времени на сборку каркаса
ekf_iter = 10
q = 0.01
r = 0.01

[topology]
k = 7
