[network]
nodes = 10
space_min = 0.0
space_max = 50000.0 # Объекты разнесены на 50 км
gps_err = 150.0
dist_err = 15.0

[hyperparams]
alpha = 5.0         # Огромный шаг для огромных расстояний
lambda = 0.1
eps = 0.5           # Останавливаемся, если узлы дрожат в пределах полуметра
max_iter = 2000
ekf_iter = 10
q = 1.0
r = 225.0

[topology]
k = 7
