[network]
nodes = 50          # Стресс-тест для CPU и RAM
space_min = 0.0
space_max = 100.0
gps_err = 5.0
dist_err = 1.0

[hyperparams]
alpha = 0.005       # Чем больше связей(пружин), тем меньше должен быть шаг
lambda = 0.3
eps = 0.0001
max_iter = 1500     # Ограничиваем, чтобы не ждать вечность
ekf_iter = 3        # Всего 3 такта EKF, так как матрица огромная
q = 0.05
r = 1.0
